import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Geekster Assignment",
  description: "Generated by Maharnav Deka",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className="bg-gray-900">
      
      <body className={inter.className}>
        <Navbar/ >
        {children}
       
        </body>
    </html>
  );
}
